export const categoriesArtists = [
    {
        id: 0,
        title: 'Portrait',
        pass: false,
        progress: 0,
        previewImage: '../images/categories/artists/001.jpg',
        startImageIndex: 0,
        endImageIndex: 9,
    },
    {
        id: 1,
        title: 'Landscape',
        pass: false,
        progress: 0,
        previewImage: '../images/categories/artists/002.jpg',
        startImageIndex: 10,
        endImageIndex: 19,
    },
    {
        id: 2,
        title: 'Still Life',
        pass: false,
        progress: 0,
        previewImage: '../images/categories/artists/003.jpg',
        startImageIndex: 20,
        endImageIndex: 29,
    },
    {
        id: 3,
        title: 'Graphic',
        pass: false,
        progress: 0,
        previewImage: '../images/categories/artists/004.jpg',
        startImageIndex: 30,
        endImageIndex: 39,
    },
    {
        id: 4,
        title: 'Antique',
        pass: false,
        progress: 0,
        previewImage: '../images/categories/artists/005.jpg',
        startImageIndex: 40,
        endImageIndex: 49,
    },
    {
        id: 5,
        title: 'Avant-Garde',
        pass: false,
        progress: 0,
        previewImage: '../images/categories/artists/006.jpg',
        startImageIndex: 50,
        endImageIndex: 59,
    },
    {
        id: 6,
        title: 'Renaissance',
        pass: false,
        progress: 0,
        previewImage: '../images/categories/artists/007.jpg',
        startImageIndex: 60,
        endImageIndex: 69,
    },
    {
        id: 7,
        title: 'Surrealism',
        pass: false,
        progress: 0,
        previewImage: '../images/categories/artists/008.jpg',
        startImageIndex: 70,
        endImageIndex: 79,
    },
    {
        id: 8,
        title: 'Kitsch',
        pass: false,
        progress: 0,
        previewImage: '../images/categories/artists/009.jpg',
        startImageIndex: 80,
        endImageIndex: 89,
    },
    {
        id: 9,
        title: 'Minimalism',
        pass: false,
        progress: 0,
        previewImage: '../images/categories/artists/010.jpg',
        startImageIndex: 90,
        endImageIndex: 99,
    },
    {
        id: 10,
        title: 'Avantgarde',
        pass: false,
        progress: 0,
        previewImage: '../images/categories/artists/011.jpg',
        startImageIndex: 100,
        endImageIndex: 109,
    },
    {
        id: 11,
        title: 'Industrial',
        pass: false,
        progress: 0,
        previewImage: '../images/categories/artists/012.jpg',
        startImageIndex: 110,
        endImageIndex: 119,
    }];
export const categoriesPictures = [
    {
        id: 12,
        title: 'Portrait',
        pass: false,
        progress: 0,
        previewImage: '../images/categories/pictures/01.jpg',
        startImageIndex: 120,
        endImageIndex: 129,
    },
    {
        id: 13,
        title: 'Landscape',
        pass: false,
        progress: 0,
        previewImage: '../images/categories/pictures/02.jpg',
        startImageIndex: 130,
        endImageIndex: 139,
    },
    {
        id: 14,
        title: 'Still Life',
        pass: false,
        progress: 0,
        previewImage: '../images/categories/pictures/03.jpg',
        startImageIndex: 140,
        endImageIndex: 149,
    },
    {
        id: 15,
        title: 'Graphic',
        pass: false,
        progress: 0,
        previewImage: '../images/categories/pictures/04.jpg',
        startImageIndex: 150,
        endImageIndex: 159,
    },
    {
        id: 16,
        title: 'Antique',
        pass: false,
        progress: 0,
        previewImage: '../images/categories/pictures/05.jpg',
        startImageIndex: 160,
        endImageIndex: 169,
    },
    {
        id: 17,
        title: 'Avant-Garde',
        pass: false,
        progress: 0,
        previewImage: '../images/categories/pictures/06.jpg',
        startImageIndex: 170,
        endImageIndex: 179,
    },
    {
        id: 18,
        title: 'Renaissance',
        pass: false,
        progress: 0,
        previewImage: '../images/categories/pictures/07.jpg',
        startImageIndex: 180,
        endImageIndex: 189,
    },
    {
        id: 19,
        title: 'Surrealism',
        pass: false,
        progress: 0,
        previewImage: '../images/categories/pictures/08.jpg',
        startImageIndex: 190,
        endImageIndex: 199,
    },
    {
        id: 20,
        title: 'Kitsch',
        pass: false,
        progress: 0,
        previewImage: '../images/categories/pictures/09.jpg',
        startImageIndex: 200,
        endImageIndex: 209,
    },
    {
        id: 21,
        title: 'Minimalism',
        pass: false,
        progress: 0,
        previewImage: '../images/categories/pictures/10.jpg',
        startImageIndex: 210,
        endImageIndex: 219,
    },
    {
        id: 22,
        title: 'Avantgarde',
        pass: false,
        progress: 0,
        previewImage: '../images/categories/pictures/11.jpg',
        startImageIndex: 220,
        endImageIndex: 229,
    },
    {
        id: 23,
        title: 'Industrial',
        pass: false,
        progress: 0,
        previewImage: '../images/categories/pictures/12.jpg',
        startImageIndex: 230,
        endImageIndex: 239,
    }

]
